### ISSUE TITLE
Dependencies are missing from package.json

### ISSUE THREAD

**Issue by mike-zorn** [yusuf-azer/yaml2properties#1]
Dependencies are missing from the `package.json`. As a result, I get an error about `commander` not being installed.

```
$ npm i -g yaml2properties
/Users/mikeatkins/.nvm/versions/node/v6.12.0/bin/yaml2properties -> /Users/mikeatkins/.nvm/versions/node/v6.12.0/lib/node_modules/yaml2properties/src/index.js
/Users/mikeatkins/.nvm/versions/node/v6.12.0/lib
└── yaml2properties@1.0.1

$ yaml2properties -h
module.js:471
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mikeatkins/.nvm/versions/node/v6.12.0/lib/node_modules/yaml2properties/src/index.js:6:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by yusufawork** [comment]
Hi, thnx for reporting on this issue
I will look into this and fix it as soon as possible.

**Comment by youmk1919** [comment]
have you fixed that ?
